### ISSUE TITLE
VNC and Logs not showing in selenoid-UI

### ISSUE THREAD

**Issue by NathanFRuiz** [aerokube/ggr#359]
I'm trying to build a POC for a selenoid cluster with ggr proxy and selenoid-UI, I've managed to make it work, however the VNC and logs do not show in selenoid-UI

from logs i'm getting ws pointing to ggr-ui, shouldn't it be to ggr? As for the vide request i'm not sure if it is related

```
selenoid-ui_1               | 2022/03/31 13:12:10 [WS_PROXY] [/ws/logs/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c] [ws://ggr-ui:8888/logs/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c]
selenoid-ui_1               | 2022/03/31 13:12:10 [WS_PROXY] [/logs/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c] [CLOSED]
selenoid-ui_1               | 2022/03/31 13:12:10 [WS_PROXY] [/ws/vnc/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c] [ws://ggr-ui:8888/vnc/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c]
selenoid-ui_1               | 2022/03/31 13:12:10 [WS_PROXY] [/vnc/1f8ac2fbb819fa8bd83b9d15bf3796b80ac29e871a605c613eab3a7ed4d7ae2c] [CLOSED]
ggr_1                       | 2022/03/31 13:14:22 [33] [-] [INVALID_VIDEO_REQUEST_URL] [test] [17.21.0.5] [/video/] [-] [-] [-] [-]
ggr_1                       | 2022/03/31 13:14:27 [34] [-] [INVALID_VIDEO_REQUEST_URL] [test] [17.21.0.5] [/video/] [-] [-] [-] [-]


```
this is my docker-compose (I found it weird that I had to pass the user:password to the --status-uri otherwise it wouldn't work, but that won't affect us in prod as we only have one user)

```
version: '3'
services:
  ggr:
    restart: always
    image: aerokube/ggr
    network_mode: bridge
    links:
      - ggr-ui
      - selenoid
    ports:
      - "4446:4446"
    volumes:
      - "./grid-router:/etc/grid-router:ro"
    command: ["-quotaDir", "/etc/grid-router/quota", "-listen", ":4446"]
  ggr-ui:
    restart: always
    network_mode: bridge
    links:
      - selenoid
    image: aerokube/ggr-ui
    ports:
      - "8888:8888"
    volumes:
      - "./grid-router:/etc/grid-router:ro"
  selenoid:
    restart: always
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/selenoid-conf:/etc/selenoid/" # assumes selenoid-conf contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "100","--container-network","bridge"]
    deploy:
      resources:
  selenoid-ui:
    restart: always
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - ggr-ui
      - ggr
    ports:
      - "8080:8080"
    deploy:
      resources:
    command: ["--selenoid-uri", "http://test:test@ggr:4446", "--status-uri", "http://test:test@ggr-ui:8888"]
  selenoid_chrome_99_image:
    image: "selenoid/vnc:chrome_99.0"
    entrypoint: ["sleep", "5"]
```

quota - test.xml

```<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="99.0">
    <version number="99.0">
        <region name="1">
            <host name="selenoid" port="4444" vnc="ws://selenoid:4444/vnc" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```
